## Artificial Neural Network (ANN)
An artificial neural network is an attempt to simulate the network of neurons that make up a human brain so that the computer will be able to learn things and make decisions in a humanlike manner. ANNs are created by programming regular computers to behave as though they are interconnected brain cells.

### Building Neural Network using Keras for binary classification

### Binary Classifications
Binary or binomial classification is the task of classifying the elements of a given set into two groups (predicting which group each one belongs to) on the basis of a classification rule.


## What is Keras?
Keras is a high-level neural network API which is written in Python and it wraps the efficient numerical computation libraries <b>Theano and TensorFlow</b> and allows you to define and train neural network models in just a few lines of code.


Keras can be used as a deep learning library because it also support <b>Convolutional and Recurrent Neural Networks</b>

###  

## For binary classification we are using Bank Customers data.

There are <b>10000 observations with 13 input variables and 1 output variable</b>.
Using this dataset we will build a model which will predict whether the customer will leave the bank or not.

### Below are the details of cutomer.

#### Variables Name:
1. RowNumber
2. CustomerId
3. Surname
4. CreditScore
5. Geography
6. Gender
7. Age(years)
8. Tenure
9. Balance
10. NumOfProducts
11. HasCrCard
12. IsActiveMember
13. EstimatedSalary
14. Exited(Target variable)

## Loading Dataset

First import the basic libraries
1. pandas.
2. numpy.
3. sklearn

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

dataset = pd.read_csv('Customer_data.csv',delimiter=',')

### Describe the dataset for better understanding

In [2]:
dataset.describe(include='all')

RowNumber    CustomerId Surname   CreditScore Geography Gender  \
count   10000.00000  1.000000e+04   10000  10000.000000     10000  10000   
unique          NaN           NaN    2932           NaN         3      2   
top             NaN           NaN   Smith           NaN    France   Male   
freq            NaN           NaN      32           NaN      5014   5457   
mean     5000.50000  1.569094e+07     NaN    650.528800       NaN    NaN   
std      2886.89568  7.193619e+04     NaN     96.653299       NaN    NaN   
min         1.00000  1.556570e+07     NaN    350.000000       NaN    NaN   
25%      2500.75000  1.562853e+07     NaN    584.000000       NaN    NaN   
50%      5000.50000  1.569074e+07     NaN    652.000000       NaN    NaN   
75%      7500.25000  1.575323e+07     NaN    718.000000       NaN    NaN   
max     10000.00000  1.581569e+07     NaN    850.000000       NaN    NaN   

                 Age        Tenure        Balance  NumOfProducts    HasCrCard  \
count   10000.000000  10000.000000   10000.000000   10000.000000  10000.00000   
unique           NaN           NaN            NaN            NaN          NaN   
top              NaN           NaN            NaN            NaN          NaN   
freq             NaN           NaN            NaN            NaN          NaN   
mean       38.921800      5.012800   76485.889288       1.530200      0.70550   
std        10.487806      2.892174   62397.405202       0.581654      0.45584   
min        18.000000      0.000000       0.000000       1.000000      0.00000   
25%        32.000000      3.000000       0.000000       1.000000      0.00000   
50%        37.000000      5.000000   97198.540000       1.000000      1.00000   
75%        44.000000      7.000000  127644.240000       2.000000      1.00000   
max        92.000000     10.000000  250898.090000       4.000000      1.00000   

        IsActiveMember  EstimatedSalary        Exited  
count     10000.000000     10000.000000  10000.000000  
unique             NaN              NaN           NaN  
top                NaN              NaN           NaN  
freq               NaN              NaN           NaN  
mean          0.515100    100090.239881      0.203700  
std           0.499797     57510.492818      0.402769  
min           0.000000        11.580000      0.000000  
25%           0.000000     51002.110000      0.000000  
50%           1.000000    100193.915000      0.000000  
75%           1.000000    149388.247500      0.000000  
max           1.000000    199992.480000      1.000000

### Note

As we can see that all features are not numerical and we do have categorical data. As we have categorical variables we need to do some data conversion of categorical variables and also we have to do some <b>feature engineering</b> on our dataset to optimize our model accuracy by providing best features to our model while training.


### What is Feature Engineering?

Feature engineering is a part of data pre-processing, where we will analyze or understand our dataset and try to find the strongest relationship of a feature with the target variable. If all feature has strong relationships with target then we don't do any update on our dataset else we will remove those columns from the dataset which are not impacting on the target variable.


###  

### Analyzing Dataset

In [3]:
dataset.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

### Observation
1. Here We can see that <b>RowNumber,CustomerId and Surname</b> are not impacting our target variable because the decision of a customer to leave the bank does not depend on the <b>customer surname and customerid</b>. So we can consider this as <b>weak features</b> in our dataset which will minimize the accuracy of our model.
2. We can also see that <b>Geography</b> and <b>Gender</b> are categorical data so we need to do data conversion.

###  

### Modifying the dataset on the above observation

#### Removing CustomerId and Surname

In [4]:
# Features (Indepenndent Variable)
X = dataset.iloc[:, 3:13].values

# Target (Dependent Varaiable)
Y = dataset.iloc[:,-1].values

# After Removing CustomerId and Surname
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


#### Data Conversion

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X1 = LabelEncoder()
X[:, 1] = labelencoder_X1.fit_transform(X[:, 1])

labelencoder_X2 = LabelEncoder()
X[:, 2] = labelencoder_X1.fit_transform(X[:, 2])

# After Data Conversion
print(X)

[[619 0 0 ... 1 1 101348.88]
 [608 2 0 ... 0 1 112542.58]
 [502 0 0 ... 1 0 113931.57]
 ...
 [709 0 0 ... 0 1 42085.58]
 [772 1 1 ... 1 0 92888.52]
 [792 0 0 ... 1 0 38190.78]]


###  
### Preparing Dataset for training and testing.

We now split the input features and target variables into training and test dataset. our test dataset will be 20% of our entire dataset.

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

###  
<b>Since our input features are at different scales we need to standardize the input.</b>

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(X_train)
x_test = sc.fit_transform(X_test)

### Implementation of keras

We have preprocessed the data and we are now ready to build the neural network. Here We are using keras to build our neural network. 

So let's import the keras library to create our first neural network layers.

To Create our neural network:-
1. We will use Sequential model to build our neural network.
2. We will use Dense library to build input, hidden and output layers of a neural network.    


### Model Architecture
1. <b>Layers</b><br>
    We have <b>10 input features</b> and one target variable. <b>2 Hidden layers</b>. Each hidden layer will have <b>6 nodes.</b><br><br>

2. <b>Activation Function</b><br>
    <b>ReLu</b> will be the activation function for hidden layers. As this is a binary classification problem we will use <b>sigmoid as the activation function</b>.<br><br>

3. <b>Loss Function</b><br>
    As this is a binary classification problem, we use <b>binary_crossentropy</b> to calculate the loss function between the actual output and the predicted output.<br><br>

4. <b>Optimizer</b><br>
    To optimize our neural network we use <b>Adam</b>. Adam stands for Adaptive moment estimation. Adam is a combination of RMSProp + Momentum.
        
<b>we use accuracy as the metrics to measure the performance of the model.</b>



 ###  

## Graphical Representation Of Neural Network Architecture 

<img src='Neural_Net_Arch.png'>

In [8]:
import keras
from keras.models import Sequential
from keras.layers import Dense

classifier = Sequential()
classifier.add(Dense(output_dim=6, activation='relu'))
classifier.add(Dense(output_dim=6, activation='relu'))
classifier.add(Dense(output_dim=1 ,activation='sigmoid'))

classifier.compile(
                    optimizer='adam',
                    loss = 'binary_crossentropy',
                    metrics = ['accuracy']
                )

Using TensorFlow backend.


Instructions for updating:
Colocations handled automatically by placer.


C:\Users\mithlesh.kumar\AppData\Local\Continuum\anaconda3\envs\tensorflow_env\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6)`
  
C:\Users\mithlesh.kumar\AppData\Local\Continuum\anaconda3\envs\tensorflow_env\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6)`
  import sys
C:\Users\mithlesh.kumar\AppData\Local\Continuum\anaconda3\envs\tensorflow_env\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1)`
  


### Model Training
Now we are going to fit our training data to the model we created. We use a batch_size of 10. 
This implies that we use 10 samples per gradient update.

We iterate over 50 epochs to train the model. An epoch is an iteration over the entire data set.

In [9]:
classifier.fit(x_train, y_train, batch_size=10, epochs=50)

Instructions for updating:
Use tf.cast instead.
Epoch 1/50
8000/8000 [==============================] - 1s 138us/step - loss: 0.5286 - acc: 0.7627
Epoch 2/50
8000/8000 [==============================] - 1s 82us/step - loss: 0.4294 - acc: 0.8101
Epoch 3/50
8000/8000 [==============================] - 1s 105us/step - loss: 0.3985 - acc: 0.8125
Epoch 4/50
8000/8000 [==============================] - 1s 83us/step - loss: 0.3855 - acc: 0.8175
Epoch 5/50
8000/8000 [==============================] - 1s 82us/step - loss: 0.3788 - acc: 0.8260
Epoch 6/50
8000/8000 [==============================] - 1s 82us/step - loss: 0.3748 - acc: 0.8317
Epoch 7/50
8000/8000 [==============================] - 1s 82us/step - loss: 0.3726 - acc: 0.8336
Epoch 8/50
8000/8000 [==============================] - 1s 83us/step - loss: 0.3705 - acc: 0.8351
Epoch 9/50
8000/8000 [==============================] - 1s 88us/step - loss: 0.3682 - acc: 0.8376
Epoch 10/50
8000/8000 [==============================] - 1s 84us/ste

#### As we can see that the accuracy of our model is 86%  in 50 epocs.

<br><b>We can also evaluate the loss value & metrics values for the model in test mode using evaluate function</b></br>

In [10]:
eval_model=classifier.evaluate(x_train, y_train)
eval_model

8000/8000 [==============================] - 0s 20us/step


[0.3353754553794861, 0.86275]

### Model Testing

Now we have trained model with us, so its time to test our model on test dataset.
We now predict the output for our test dataset. If the prediction is greater than 0.5 then the output is 1(True) else the output is 0(False)

If the output of our model is <b>True</b> then customer will close his/her account.

In [11]:
y_pred=classifier.predict(x_test)
result=y_pred>0.5
print(result)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


###  

In [12]:
# Random Check
new_pre = sc.transform(np.array([[519,0,0,32,1,0.1,0,1,1,23000]]))
result = classifier.predict(new_pre)>0.5
print(result[0][0])

True


### Above are the output of our model. If you want to do some random test please update the values in random section accordingly